apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  namespace: demo
  labels:
    app: demo-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-01
  template:
    metadata:
      labels:
        app: demo-01
    spec:
      containers:
      - image: httpd:2.4.46-alpine
        name: apache




